/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class ru_waterdist_Pipec */

#ifndef _Included_ru_waterdist_Pipec
#define _Included_ru_waterdist_Pipec
#ifdef __cplusplus
extern "C" {
#endif

#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG  , "!!!!!!!!!!!!!", __VA_ARGS__)
      
/*
 * Class:     ru_waterdist_Pipec
 * Method:    pipec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_waterdist_Pipec_pipec
  (JNIEnv *, jobject) {
  
  /*
  	if (mkfifo("/data/data/ru.waterdist/test_fifo1", S_IRWXU) >= 0 )
    {


    LOGD("mkfifo!!!!!!!!");


} else {
 LOGD("noooooooo");
}
*/
  
    int fp;
    char buf[255];
    int l; // read length

    buf[0] = '\0'; // in case there is nothing to read
    buf[255] = '\0'; // garentee a end-of-line

    fp = open("/data/data/ru.waterdist/test_fifo1", O_RDWR);
    if(fp == -1) {
        LOGD("Could not open the pipe\n");
    }
    
    char q = 42;
    write(fp, &q, 1);

/*
    do {
        l = read(fp, buf, 254);
        LOGD(buf);
    } while (l > 0);
*/
    close(fp);
  
  
  /*
  	   pid_t pid;
       int mypipe[2];
     
      LOGD("HOHOHOHO&&&???");
       if (pipe (mypipe))
         {
           LOGD("Pipe failed.");
         } else {
        	 LOGD("Pipe CRETAED.");
         }
  */
  }
  
  JNIEXPORT void JNICALL Java_ru_waterdist_Pipec_pipec2
  (JNIEnv *, jobject) {
  
	FILE * pFile;
  pFile = fopen ("/data/data/ru.waterdist/test_fifo","w");
  if (pFile!=NULL)
  {
  LOGD("PUTS");
    fputs ("fopen example",pFile);
    //fclose (pFile);
  }
  }

#ifdef __cplusplus
}
#endif
#endif
